version: 2

registries:
  composer:
    type: composer-repository
    url: "https://satis.spatie.be"
    username: ${{secrets.COMPOSER_AUTH_USERNAME}}
    password: ${{secrets.COMPOSER_AUTH_PASSWORD}}

updates:
  - package-ecosystem: "composer"
    registries:
      - composer
    directory: "/"
    schedule:
      interval: "daily"
